use mydb;

/* 사용자정보 */
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    lv INT,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* 코드 */
CREATE TABLE IF NOT EXISTS codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code_grp VARCHAR(4) NOT NULL UNIQUE,
    code VARCHAR(4),
    code_desc TEXT,
    temproary_1 VARCHAR(100),
    temproary_2 VARCHAR(100),
    use_yn CHAR(1) DEFAULT 'Y',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* 영웅 */
CREATE TABLE IF NOT EXISTS heroes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hero_name VARCHAR(20) NOT NULL UNIQUE,
    hero_rank VARCHAR(1),
    hero_type VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* 유저 스펙 */
CREATE TABLE IF NOT EXISTS user_specs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    spec_type VARCHAR(20),
    spec_subtype VARCHAR(20),
    spec_value INT,
    spec_subvalue INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* 공성전 */
CREATE TABLE IF NOT EXISTS user_siege (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    std_date VARCHAR(8) NOT NULL,
    score INT,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_date (user_id, std_date)
);

/* 길드전 */
CREATE TABLE IF NOT EXISTS user_guildwar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    setting_yn CHAR(1) DEFAULT 'N',
    play_yn CHAR(1) DEFAULT 'N',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* 중요도 */
CREATE TABLE IF NOT EXISTS spec_priority (
    id INT AUTO_INCREMENT PRIMARY KEY,
    spec_type VARCHAR(4) NOT NULL UNIQUE,
    priority_val DECIMAL(10,2),
    use_yn CHAR(1) DEFAULT 'Y',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* 유저 영웅 */
CREATE TABLE IF NOT EXISTS user_heroes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    hero_id INT NOT NULL,
    hero_grade INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_hero (user_id, hero_id)
);